apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-assistant
  labels:
    app: news-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-assistant
  template:
    metadata:
      labels:
        app: news-assistant
    spec:
      containers:
      - name: news-assistant
        image: news-assistant:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: news-assistant-secrets
              key: NEWS_API_KEY
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: news-assistant-secrets
              key: GROQ_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 5
          

